---
#
# Ansible managed
#
repository:
  description: Install and configure tigervnc on your system.
  homepage: https://robertdebock.nl/
  topics: tigervnc, networking, ansible, molecule, tox, playbook
