---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Test port 5901
      ansible.builtin.wait_for:
        port: 5901

    - name: Show testing instruction
      ansible.builtin.debug:
        msg: "Please run: vncviewer {{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}:5901"
